FROM python:3.9-bullseye

WORKDIR /Awtobot

# copy local files
COPY [".", "/Awtobot"]

RUN apt-get update -y && apt-get install nodejs npm -y

RUN npm install -g n

RUN n lts

RUN python -c 'import sys;print("%x" % sys.maxsize, sys.maxsize > 2**32)'

# install server dependencies
RUN python3 -m pip install -r ./requirements.txt

RUN npm install --silent


RUN node -v

CMD ["npm", "start"]
